import React, { useState, useEffect } from 'react';
import { FamilyMember, PassportRecord, IdentityRecord, FamilyDocument, IdCountry } from '../types';
import {
  Plus, Pencil, Check, X, Globe, ShieldCheck, Car, MapPin, BookOpen, Eye, Maximize2, Camera,
} from 'lucide-react';
import ImageLightbox from './ImageLightbox';
import ShowCardModal from './ShowCardModal';
import DocumentScannerModal, { ScannedFile } from './DocumentScannerModal';
import ConfirmDeleteButton from './ConfirmDeleteButton';
import PrivacyNote from './PrivacyNote';
import EmptyState from './EmptyState';

// Data needed to pop open the full-screen "show this to someone" card — a border
// officer, receptionist, ticket inspector. Shared by the passport rows and the
// key identity-number fields (e-card, residence permit) below.
interface ShowCardData {
  title: string;
  subtitle?: string;
  fields: { label: string; value: string; mono?: boolean; big?: boolean }[];
  scanSrc?: string;
}

const newId = () => Date.now().toString() + Math.floor(Math.random() * 1000);

// Common ways a country ends up written — the passport record's "country" field
// is free text (typed by a person or generated by the AI) and a scanned
// document's name is a SEPARATE piece of free text, so "United Kingdom" and "UK"
// need to be recognized as the same country even though neither string literally
// contains the other. Anything not listed here still falls back to plain
// substring matching below, so this can only ever improve a match, never break one.
const COUNTRY_ALIASES: Record<string, string[]> = {
  uk: ['united kingdom', 'great britain', 'britain', 'england', 'scotland', 'wales', 'northern ireland', 'uk', 'gb'],
  za: ['south africa', 'south african', 'rsa', 'za'],
  at: ['austria', 'austrian', 'österreich', 'at'],
  us: ['united states', 'america', 'american', 'usa', 'us'],
  de: ['germany', 'german', 'deutschland', 'de'],
  fr: ['france', 'french', 'fr'],
  ie: ['ireland', 'irish', 'ie'],
  au: ['australia', 'australian', 'au'],
  ca: ['canada', 'canadian', 'ca'],
  nz: ['new zealand', 'nz'],
};

function countryToken(raw: string): string | undefined {
  const s = raw.toLowerCase();
  for (const [token, aliases] of Object.entries(COUNTRY_ALIASES)) {
    if (aliases.some(a => s.includes(a))) return token;
  }
  return undefined;
}

// Link a passport row to its scanned image: an ID-category document that mentions
// "passport" (and the country when known). Lets us show a "view scan" icon next to
// the number so the document behind it is one tap away.
function findPassportScan(p: PassportRecord, docs?: FamilyDocument[]): FamilyDocument | undefined {
  const idDocs = (docs || []).filter(d => d.category === 'ID' && d.fileData && /passport/i.test(d.name));
  if (idDocs.length === 0) return undefined;
  const country = (p.country || '').toLowerCase();
  const token = country ? countryToken(country) : undefined;
  const byAlias = token ? idDocs.find(d => countryToken(d.name) === token) : undefined;
  return byAlias
    || (country && idDocs.find(d => d.name.toLowerCase().includes(country)))
    || (idDocs.length === 1 ? idDocs[0] : undefined);
}

// Same idea, for the identity-number fields below (e-Card, tax number, residence
// permit, etc.) — each field maps to a keyword pattern its scanned document's name
// is expected to match (English or German).
const IDENTITY_SCAN_PATTERNS: Partial<Record<keyof IdentityRecord, RegExp>> = {
  eCardNumber: /e-?card/i,
  taxNumber: /tax|steuer|sars/i,
  studentNumber: /student|matrikel/i,
  schoolRegNumber: /school|sch(?:ü|ue)ler/i,
  residencePermitNumber: /residence|aufenthalt|visa|permit/i,
  nationalIdNumber: /national\s*id|id\s*card|personalausweis|smart id|id book/i,
  citizenshipCertNumber: /citizenship|staatsb(?:ü|ue)rger/i,
  driversLicenseNumber: /driver|f(?:ü|ue)hrerschein/i,
  birthCertNumber: /birth cert/i,
  medicalAidNumber: /medical aid|health insurance/i,
};

// Exported so the Emergency essentials card can resolve the SAME scan for the
// health-insurance number without a second, drifting copy of these rules.
export function findIdentityScan(field: keyof IdentityRecord, docs?: FamilyDocument[]): FamilyDocument | undefined {
  const pattern = IDENTITY_SCAN_PATTERNS[field];
  if (!pattern) return undefined;
  const idDocs = (docs || []).filter(d => d.category === 'ID' && d.fileData);
  let candidates = idDocs.filter(d => pattern.test(d.name));
  // The generic "national ID" field also catches anything explicitly labelled "ID"
  // as its own word — "Nomvula ID", "Mama ID and Driver's License" — the single
  // most common way people actually name an ID-document scan. This ADDS to (never
  // replaces) the specific-pattern match above, so a combined "ID and Driver's
  // License" scan surfaces under both fields rather than whichever keyword the
  // regex happened to hit first.
  if (field === 'nationalIdNumber') {
    const idLabelled = idDocs.filter(d => /\bid\b/i.test(d.name));
    candidates = [...new Set([...candidates, ...idLabelled])];
  }
  if (candidates.length === 0) return undefined;
  if (candidates.length === 1) return candidates[0];
  return [...candidates].sort((a, b) => (b.uploadedAt || '').localeCompare(a.uploadedAt || ''))[0];
}

/* ─── expiry chip helper ─────────────────────────────────────────── */

function expiryChip(dateStr: string | undefined): React.ReactNode {
  if (!dateStr) return null;
  const today = new Date();
  const expiry = new Date(dateStr);
  const diffMs = expiry.getTime() - today.getTime();
  if (diffMs < 0) {
    return <span className="chip bg-rosa-100 text-rosa-700">Expired</span>;
  }
  const months = diffMs / (1000 * 60 * 60 * 24 * 30.4375);
  if (months <= 9) {
    const rounded = Math.max(1, Math.round(months));
    return <span className="chip bg-honey-100 text-honey-700">Expires in ~{rounded} month{rounded !== 1 ? 's' : ''}</span>;
  }
  return <span className="chip bg-sage-100 text-sage-700">Valid</span>;
}

/* ─── Props ──────────────────────────────────────────────────────── */

interface MemberIDsProps {
  member: FamilyMember;
  onUpdate: (patch: Partial<FamilyMember>) => void;
  onAddDocument: (memberId: string, doc: FamilyDocument) => void;
  country?: IdCountry;
  onOpenPrivacy?: () => void;
}

/* ─── Passport form ──────────────────────────────────────────────── */

interface PassportFormState {
  country: string;
  number: string;
  expiryDate: string;
  issueDate: string;
  notes: string;
}

const emptyPassportForm = (): PassportFormState => ({
  country: '',
  number: '',
  expiryDate: '',
  issueDate: '',
  notes: '',
});

const passportToForm = (p: PassportRecord): PassportFormState => ({
  country: p.country,
  number: p.number,
  expiryDate: p.expiryDate || '',
  issueDate: p.issueDate || '',
  notes: p.notes || '',
});

function PassportForm({
  initial,
  onSave,
  onCancel,
}: {
  initial?: PassportRecord;
  onSave: (p: PassportRecord) => void;
  onCancel: () => void;
}) {
  const [form, setForm] = useState<PassportFormState>(
    initial ? passportToForm(initial) : emptyPassportForm()
  );

  const set = (k: keyof PassportFormState) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) =>
    setForm(prev => ({ ...prev, [k]: e.target.value }));

  const save = () => {
    if (!form.country.trim() && !form.number.trim()) { onCancel(); return; }
    onSave({
      id: initial?.id || newId(),
      country: form.country.trim(),
      number: form.number.trim(),
      expiryDate: form.expiryDate || undefined,
      issueDate: form.issueDate || undefined,
      notes: form.notes.trim() || undefined,
    });
  };

  return (
    <div className="p-3.5 rounded-2xl border border-clay-200 bg-clay-50/60 space-y-2.5">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
        <input
          autoFocus
          className="field"
          placeholder="Country  (e.g. Austria, South Africa)"
          value={form.country}
          onChange={set('country')}
        />
        <input
          className="field font-mono"
          placeholder="Passport number"
          value={form.number}
          onChange={set('number')}
        />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
        <div>
          <label className="field-label">Issue date</label>
          <input type="date" className="field" value={form.issueDate} onChange={set('issueDate')} />
        </div>
        <div>
          <label className="field-label">Expiry date</label>
          <input type="date" className="field" value={form.expiryDate} onChange={set('expiryDate')} />
        </div>
      </div>
      <input className="field" placeholder="Notes (optional)" value={form.notes} onChange={set('notes')} />
      <div className="flex justify-end gap-2">
        <button onClick={onCancel} className="btn-quiet text-xs px-3 py-1.5">
          <X className="w-3.5 h-3.5" /> Cancel
        </button>
        <button onClick={save} className="btn-primary text-xs px-3 py-1.5">
          <Check className="w-3.5 h-3.5" /> Save
        </button>
      </div>
    </div>
  );
}

/* ─── Passports section ──────────────────────────────────────────── */

function PassportsSection({
  passports,
  onChange,
  documents,
  onViewScan,
  memberName,
  onShowCard,
}: {
  passports: PassportRecord[];
  onChange: (next: PassportRecord[]) => void;
  documents?: FamilyDocument[];
  onViewScan: (src: string) => void;
  memberName: string;
  onShowCard: (data: ShowCardData) => void;
}) {
  const [adding, setAdding] = useState(false);
  const [editId, setEditId] = useState<string | null>(null);

  const handleAdd = (p: PassportRecord) => {
    onChange([...passports, p]);
    setAdding(false);
  };

  const handleUpdate = (p: PassportRecord) => {
    onChange(passports.map(x => x.id === p.id ? p : x));
    setEditId(null);
  };

  const handleDelete = (id: string) => {
    onChange(passports.filter(x => x.id !== id));
  };

  return (
    <section className="card p-5 space-y-4">
      <div className="flex items-center justify-between pb-3 border-b border-cream-200">
        <h3 className="section-label flex items-center gap-1.5">
          <Globe className="w-3.5 h-3.5" /> Passports
        </h3>
        <button
          onClick={() => { setAdding(true); setEditId(null); }}
          className="btn-primary text-xs px-3 py-1.5"
        >
          <Plus className="w-3.5 h-3.5" /> Add
        </button>
      </div>

      {adding && (
        <PassportForm
          onSave={handleAdd}
          onCancel={() => setAdding(false)}
        />
      )}

      {passports.length === 0 && !adding ? (
        <EmptyState icon={Globe} title="No passports yet — add one for each nationality." />
      ) : (
        <div className="space-y-2.5">
          {passports.map(p => editId === p.id ? (
            <div key={p.id}>
              <PassportForm
                initial={p}
                onSave={handleUpdate}
                onCancel={() => setEditId(null)}
              />
            </div>
          ) : (
            <div key={p.id} className="p-3.5 rounded-2xl border border-cream-200 bg-white flex flex-wrap items-start justify-between gap-3">
              <div className="min-w-0 space-y-1">
                <div className="flex flex-wrap items-center gap-2">
                  <p className="text-[14px] font-semibold text-ink-900">{p.country || 'Unknown country'}</p>
                  {expiryChip(p.expiryDate)}
                </div>
                <p className="font-mono tabular-nums text-[13px] text-ink-600 break-all">{p.number || '—'}</p>
                {(p.issueDate || p.expiryDate) && (
                  <p className="tabular-nums text-[12px] text-ink-400">
                    {p.issueDate ? `Issued ${p.issueDate}` : ''}
                    {p.issueDate && p.expiryDate ? ' · ' : ''}
                    {p.expiryDate ? `Expires ${p.expiryDate}` : ''}
                  </p>
                )}
                {p.notes && <p className="text-[12px] text-ink-500">{p.notes}</p>}
              </div>
              <div className="flex items-center gap-1 shrink-0">
                <button
                  onClick={() => onShowCard({
                    title: p.country ? `${p.country} passport` : 'Passport',
                    subtitle: memberName,
                    fields: [
                      { label: 'Passport no.', value: p.number || '—', mono: true, big: true },
                      { label: 'Expiry', value: p.expiryDate || '—' },
                    ],
                    scanSrc: findPassportScan(p, documents)?.fileData,
                  })}
                  className="flex items-center gap-1 px-2 py-1.5 text-[11px] font-semibold text-clay-600 hover:text-clay-800 hover:bg-clay-50 rounded-lg"
                  title="Show this passport"
                >
                  <Maximize2 className="w-3.5 h-3.5" /> Show
                </button>
                <button
                  onClick={() => { setEditId(p.id); setAdding(false); }}
                  className="p-1.5 text-ink-400 hover:text-ink-700 hover:bg-cream-100 rounded-lg"
                  title="Edit"
                >
                  <Pencil className="w-3.5 h-3.5" />
                </button>
                <ConfirmDeleteButton
                  onConfirm={() => handleDelete(p.id)}
                  ariaLabel={`Delete ${p.country || 'this'} passport`}
                />
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

/* ─── Identity section ───────────────────────────────────────────── */

// Field label with an optional "view scan" eye icon, shown only when a matching
// scanned document exists — keeps the common no-scan case visually unchanged.
function IdentityLabelRow({
  label,
  scan,
  onViewScan,
  viewTitle,
}: {
  label: string;
  scan: FamilyDocument | undefined;
  onViewScan: (src: string) => void;
  viewTitle: string;
}) {
  if (!scan) return <label className="field-label">{label}</label>;
  return (
    <div className="flex items-center justify-between mb-1.5">
      <label className="text-[13px] font-semibold text-ink-600">{label}</label>
      <button
        onClick={() => onViewScan(scan.fileData!)}
        className="p-1.5 text-clay-500 hover:text-clay-700 hover:bg-clay-50 rounded-lg"
        title={viewTitle}
      >
        <Eye className="w-3.5 h-3.5" />
      </button>
    </div>
  );
}

const COUNTRY_SECTION_TITLE: Record<IdCountry, string> = {
  AT: 'Austrian & national IDs',
  ZA: 'South African & national IDs',
  UK: 'UK & national IDs',
  US: 'US & national IDs',
  other: 'IDs & national documents',
};

function IdentitySection({
  identity,
  onChange,
  documents,
  onViewScan,
  memberName,
  onShowCard,
  country,
  onScanClick,
}: {
  identity: IdentityRecord;
  onChange: (next: IdentityRecord) => void;
  documents?: FamilyDocument[];
  onViewScan: (src: string) => void;
  memberName: string;
  onShowCard: (data: ShowCardData) => void;
  country: IdCountry;
  onScanClick: () => void;
}) {
  const set = (k: keyof IdentityRecord) => (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => onChange({ ...identity, [k]: e.target.value || undefined });

  const val = (k: keyof IdentityRecord) => identity[k] as string | undefined ?? '';

  return (
    <section className="card p-5 space-y-6">
      {/* Section header */}
      <div className="flex items-center justify-between gap-2 pb-3 border-b border-cream-200">
        <div className="flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-dusk-500" />
          <h3 className="section-label">{COUNTRY_SECTION_TITLE[country]}</h3>
        </div>
        <button type="button" onClick={onScanClick} className="btn-quiet text-xs px-3 py-1.5">
          <Camera className="w-3.5 h-3.5" />
          Scan an ID card
        </button>
      </div>

      {country === 'ZA' && (
        <SouthAfricanFields identity={identity} val={val} set={set} onChange={onChange} documents={documents} onViewScan={onViewScan} memberName={memberName} onShowCard={onShowCard} />
      )}
      {country === 'UK' && (
        <UKFields identity={identity} val={val} set={set} onChange={onChange} documents={documents} onViewScan={onViewScan} memberName={memberName} onShowCard={onShowCard} />
      )}
      {country === 'US' && (
        <USFields identity={identity} val={val} set={set} onChange={onChange} documents={documents} onViewScan={onViewScan} memberName={memberName} onShowCard={onShowCard} />
      )}
      {country === 'other' && (
        <GenericIdentityFields identity={identity} val={val} set={set} onChange={onChange} documents={documents} onViewScan={onViewScan} memberName={memberName} onShowCard={onShowCard} />
      )}

      {country === 'AT' && (
      <>
      {/* Austria */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-clay-600">
          <MapPin className="w-3 h-3" /> Austria
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">e-Card number</label>
              <div className="flex items-center gap-1">
                {identity.eCardNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'e-card',
                      subtitle: memberName,
                      fields: [
                        { label: 'e-Card number', value: identity.eCardNumber || '—', mono: true, big: true },
                      ],
                      scanSrc: findIdentityScan('eCardNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this e-card"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input
              className="field font-mono tabular-nums"
              placeholder="e.g. 1234 010090 AT"
              value={val('eCardNumber')}
              onChange={set('eCardNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <label className="field-label">Sozialversicherungsnummer (SV)</label>
            <input
              className="field font-mono tabular-nums"
              placeholder="e.g. 1234 010190"
              value={val('svNumber')}
              onChange={set('svNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <IdentityLabelRow
              label="Tax number"
              scan={findIdentityScan('taxNumber', documents)}
              onViewScan={onViewScan}
              viewTitle="View scanned tax document"
            />
            <input
              className="field font-mono tabular-nums"
              placeholder="Steuernummer"
              value={val('taxNumber')}
              onChange={set('taxNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <IdentityLabelRow
              label="Student number"
              scan={findIdentityScan('studentNumber', documents)}
              onViewScan={onViewScan}
              viewTitle="View scanned student number document"
            />
            <input
              className="field font-mono tabular-nums"
              placeholder="Matrikelnummer"
              value={val('studentNumber')}
              onChange={set('studentNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <IdentityLabelRow
              label="School registration number"
              scan={findIdentityScan('schoolRegNumber', documents)}
              onViewScan={onViewScan}
              viewTitle="View scanned school registration document"
            />
            <input
              className="field font-mono tabular-nums"
              placeholder="Schülerausweis-Nr"
              value={val('schoolRegNumber')}
              onChange={set('schoolRegNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
        </div>
      </div>

      {/* Residence & national */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-dusk-700">
          <BookOpen className="w-3 h-3" /> Residence &amp; national
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">Residence permit number</label>
              <div className="flex items-center gap-1">
                {identity.residencePermitNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'Residence permit',
                      subtitle: memberName,
                      fields: [
                        { label: 'Residence permit number', value: identity.residencePermitNumber || '—', mono: true, big: true },
                        ...(identity.residencePermitExpiry
                          ? [{ label: 'Expiry', value: identity.residencePermitExpiry }]
                          : []),
                      ],
                      scanSrc: findIdentityScan('residencePermitNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this residence permit"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input
              className="field font-mono tabular-nums"
              placeholder="Aufenthaltstitel-Nr"
              value={val('residencePermitNumber')}
              onChange={set('residencePermitNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <label className="field-label">
              Residence permit expiry
              {identity.residencePermitExpiry && (
                <span className="ml-2">{expiryChip(identity.residencePermitExpiry)}</span>
              )}
            </label>
            <input
              type="date"
              className="field tabular-nums"
              value={val('residencePermitExpiry')}
              onChange={set('residencePermitExpiry')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <IdentityLabelRow
              label="National ID number"
              scan={findIdentityScan('nationalIdNumber', documents)}
              onViewScan={onViewScan}
              viewTitle="View scanned national ID document"
            />
            <input
              className="field font-mono tabular-nums"
              placeholder="e.g. SA ID number"
              value={val('nationalIdNumber')}
              onChange={set('nationalIdNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <IdentityLabelRow
              label="Citizenship certificate number"
              scan={findIdentityScan('citizenshipCertNumber', documents)}
              onViewScan={onViewScan}
              viewTitle="View scanned citizenship certificate"
            />
            <input
              className="field font-mono tabular-nums"
              placeholder="Staatsbürgerschaftsnachweis"
              value={val('citizenshipCertNumber')}
              onChange={set('citizenshipCertNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
        </div>
      </div>

      {/* Driving */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-sage-700">
          <Car className="w-3 h-3" /> Driving
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <IdentityLabelRow
              label="Driver's licence number"
              scan={findIdentityScan('driversLicenseNumber', documents)}
              onViewScan={onViewScan}
              viewTitle="View scanned driver's licence"
            />
            <input
              className="field font-mono tabular-nums"
              placeholder="Führerschein-Nr"
              value={val('driversLicenseNumber')}
              onChange={set('driversLicenseNumber')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
          <div>
            <label className="field-label">
              Driver's licence expiry
              {identity.driversLicenseExpiry && (
                <span className="ml-2">{expiryChip(identity.driversLicenseExpiry)}</span>
              )}
            </label>
            <input
              type="date"
              className="field tabular-nums"
              value={val('driversLicenseExpiry')}
              onChange={set('driversLicenseExpiry')}
              onBlur={() => onChange({ ...identity })}
            />
          </div>
        </div>
      </div>
      </>
      )}

      {/* Notes */}
      <div>
        <label className="field-label">Notes</label>
        <textarea
          rows={3}
          className="field font-sans"
          placeholder="Any other ID notes…"
          value={val('notes')}
          onChange={set('notes')}
          onBlur={() => onChange({ ...identity })}
        />
      </div>
    </section>
  );
}

/* ─── Country-specific field sets ───────────────────────────────────
   Share the AT section's row/scan/Show-button conventions but stay
   fully separate JSX so the existing Austrian path (the current default
   for every pre-existing account) is never touched by these additions. */

interface FieldSetProps {
  identity: IdentityRecord;
  val: (k: keyof IdentityRecord) => string;
  set: (k: keyof IdentityRecord) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
  onChange: (next: IdentityRecord) => void;
  documents?: FamilyDocument[];
  onViewScan: (src: string) => void;
  memberName: string;
  onShowCard: (data: ShowCardData) => void;
}

function SouthAfricanFields({ identity, val, set, onChange, documents, onViewScan, memberName, onShowCard }: FieldSetProps) {
  return (
    <>
      {/* Identity */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-clay-600">
          <MapPin className="w-3 h-3" /> Identity
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="field-label">ID document type</label>
            <select
              className="field"
              value={val('idDocumentType')}
              onChange={(e) => onChange({ ...identity, idDocumentType: e.target.value || undefined })}
            >
              <option value="">Select…</option>
              <option value="Smart ID Card">Smart ID Card</option>
              <option value="Green ID Book">Green ID Book</option>
              <option value="Foreign passport">Foreign passport</option>
              <option value="Other">Other</option>
            </select>
          </div>
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">SA ID number</label>
              <div className="flex items-center gap-1">
                {identity.nationalIdNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'SA ID number', subtitle: memberName,
                      fields: [{ label: 'ID number', value: identity.nationalIdNumber || '—', mono: true, big: true }],
                      scanSrc: findIdentityScan('nationalIdNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this ID"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input className="field font-mono tabular-nums" placeholder="e.g. 9001015800086" value={val('nationalIdNumber')} onChange={set('nationalIdNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Unabridged birth certificate no." scan={findIdentityScan('birthCertNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned birth certificate" />
            <input className="field font-mono tabular-nums" placeholder="Birth certificate number" value={val('birthCertNumber')} onChange={set('birthCertNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="SARS tax reference number" scan={findIdentityScan('taxNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned tax document" />
            <input className="field font-mono tabular-nums" placeholder="10-digit tax reference" value={val('taxNumber')} onChange={set('taxNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Student number" scan={findIdentityScan('studentNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned student number document" />
            <input className="field font-mono tabular-nums" placeholder="Student number" value={val('studentNumber')} onChange={set('studentNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="School registration number" scan={findIdentityScan('schoolRegNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned school registration document" />
            <input className="field font-mono tabular-nums" placeholder="School registration number" value={val('schoolRegNumber')} onChange={set('schoolRegNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
        </div>
      </div>

      {/* Residence, travel & other */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-dusk-700">
          <BookOpen className="w-3 h-3" /> Residence, travel &amp; other
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">Residence permit / visa number</label>
              <div className="flex items-center gap-1">
                {identity.residencePermitNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'Residence permit / visa', subtitle: memberName,
                      fields: [
                        { label: 'Permit/visa number', value: identity.residencePermitNumber || '—', mono: true, big: true },
                        ...(identity.residencePermitExpiry ? [{ label: 'Expiry', value: identity.residencePermitExpiry }] : []),
                      ],
                      scanSrc: findIdentityScan('residencePermitNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this permit/visa"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input className="field font-mono tabular-nums" placeholder="Permit or visa number" value={val('residencePermitNumber')} onChange={set('residencePermitNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">
              Residence permit / visa expiry
              {identity.residencePermitExpiry && <span className="ml-2">{expiryChip(identity.residencePermitExpiry)}</span>}
            </label>
            <input type="date" className="field tabular-nums" value={val('residencePermitExpiry')} onChange={set('residencePermitExpiry')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Driver's licence number" scan={findIdentityScan('driversLicenseNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned driver's licence" />
            <input className="field font-mono tabular-nums" placeholder="Driver's licence number" value={val('driversLicenseNumber')} onChange={set('driversLicenseNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">
              Driver's licence expiry
              {identity.driversLicenseExpiry && <span className="ml-2">{expiryChip(identity.driversLicenseExpiry)}</span>}
            </label>
            <input type="date" className="field tabular-nums" value={val('driversLicenseExpiry')} onChange={set('driversLicenseExpiry')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Medical aid membership number" scan={findIdentityScan('medicalAidNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned medical aid card" />
            <input className="field font-mono tabular-nums" placeholder="Medical aid member number" value={val('medicalAidNumber')} onChange={set('medicalAidNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">Medical aid scheme</label>
            <input className="field" placeholder="e.g. Discovery Health, Bonitas, GEMS" value={val('medicalAidScheme')} onChange={set('medicalAidScheme')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">Plan / option name</label>
            <input className="field" placeholder="e.g. Discovery Classic Saver" value={val('medicalAidPlanOption')} onChange={set('medicalAidPlanOption')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">Dependant code</label>
            <input className="field font-mono tabular-nums" placeholder="00 = principal member, 01, 02…" value={val('medicalAidDependantCode')} onChange={set('medicalAidDependantCode')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Citizenship certificate number" scan={findIdentityScan('citizenshipCertNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned citizenship certificate" />
            <input className="field font-mono tabular-nums" placeholder="Citizenship certificate number" value={val('citizenshipCertNumber')} onChange={set('citizenshipCertNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
        </div>
      </div>
    </>
  );
}

function GenericIdentityFields({ identity, val, set, onChange, documents, onViewScan, memberName, onShowCard }: FieldSetProps) {
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div>
          <div className="flex items-center justify-between mb-1.5">
            <label className="text-[13px] font-semibold text-ink-600">National ID number</label>
            <div className="flex items-center gap-1">
              {identity.nationalIdNumber && (
                <button
                  onClick={() => onShowCard({
                    title: 'National ID', subtitle: memberName,
                    fields: [{ label: 'ID number', value: identity.nationalIdNumber || '—', mono: true, big: true }],
                    scanSrc: findIdentityScan('nationalIdNumber', documents)?.fileData,
                  })}
                  className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                  title="Show this ID"
                >
                  <Maximize2 className="w-3 h-3" /> Show
                </button>
              )}
            </div>
          </div>
          <input className="field font-mono tabular-nums" placeholder="National ID / SSN / equivalent" value={val('nationalIdNumber')} onChange={set('nationalIdNumber')} onBlur={() => onChange({ ...identity })} />
        </div>
        <div>
          <IdentityLabelRow label="Tax number" scan={findIdentityScan('taxNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned tax document" />
          <input className="field font-mono tabular-nums" placeholder="Tax reference number" value={val('taxNumber')} onChange={set('taxNumber')} onBlur={() => onChange({ ...identity })} />
        </div>
        <div>
          <IdentityLabelRow label="Driver's licence number" scan={findIdentityScan('driversLicenseNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned driver's licence" />
          <input className="field font-mono tabular-nums" placeholder="Driver's licence number" value={val('driversLicenseNumber')} onChange={set('driversLicenseNumber')} onBlur={() => onChange({ ...identity })} />
        </div>
        <div>
          <label className="field-label">
            Driver's licence expiry
            {identity.driversLicenseExpiry && <span className="ml-2">{expiryChip(identity.driversLicenseExpiry)}</span>}
          </label>
          <input type="date" className="field tabular-nums" value={val('driversLicenseExpiry')} onChange={set('driversLicenseExpiry')} onBlur={() => onChange({ ...identity })} />
        </div>
        <div>
          <IdentityLabelRow label="Residence permit / visa number" scan={findIdentityScan('residencePermitNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned permit/visa" />
          <input className="field font-mono tabular-nums" placeholder="Permit or visa number" value={val('residencePermitNumber')} onChange={set('residencePermitNumber')} onBlur={() => onChange({ ...identity })} />
        </div>
        <div>
          <label className="field-label">
            Residence permit / visa expiry
            {identity.residencePermitExpiry && <span className="ml-2">{expiryChip(identity.residencePermitExpiry)}</span>}
          </label>
          <input type="date" className="field tabular-nums" value={val('residencePermitExpiry')} onChange={set('residencePermitExpiry')} onBlur={() => onChange({ ...identity })} />
        </div>
      </div>
    </div>
  );
}

function UKFields({ identity, val, set, onChange, documents, onViewScan, memberName, onShowCard }: FieldSetProps) {
  return (
    <>
      {/* Identity */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-clay-600">
          <MapPin className="w-3 h-3" /> Identity
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">National Insurance number</label>
              <div className="flex items-center gap-1">
                {identity.nationalIdNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'National Insurance number', subtitle: memberName,
                      fields: [{ label: 'NI number', value: identity.nationalIdNumber || '—', mono: true, big: true }],
                      scanSrc: findIdentityScan('nationalIdNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this NI number"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input className="field font-mono tabular-nums" placeholder="e.g. QQ 12 34 56 C" value={val('nationalIdNumber')} onChange={set('nationalIdNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Unabridged birth certificate no." scan={findIdentityScan('birthCertNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned birth certificate" />
            <input className="field font-mono tabular-nums" placeholder="Birth certificate number" value={val('birthCertNumber')} onChange={set('birthCertNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Tax reference (UTR)" scan={findIdentityScan('taxNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned tax document" />
            <input className="field font-mono tabular-nums" placeholder="Unique Taxpayer Reference" value={val('taxNumber')} onChange={set('taxNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Student number" scan={findIdentityScan('studentNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned student number document" />
            <input className="field font-mono tabular-nums" placeholder="Student number" value={val('studentNumber')} onChange={set('studentNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="School registration number" scan={findIdentityScan('schoolRegNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned school registration document" />
            <input className="field font-mono tabular-nums" placeholder="School registration number" value={val('schoolRegNumber')} onChange={set('schoolRegNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
        </div>
      </div>

      {/* Residence, travel & other */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-dusk-700">
          <BookOpen className="w-3 h-3" /> Residence, travel &amp; other
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">BRP / visa number</label>
              <div className="flex items-center gap-1">
                {identity.residencePermitNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'BRP / visa', subtitle: memberName,
                      fields: [
                        { label: 'BRP/visa number', value: identity.residencePermitNumber || '—', mono: true, big: true },
                        ...(identity.residencePermitExpiry ? [{ label: 'Expiry', value: identity.residencePermitExpiry }] : []),
                      ],
                      scanSrc: findIdentityScan('residencePermitNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this BRP/visa"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input className="field font-mono tabular-nums" placeholder="Biometric Residence Permit / visa number" value={val('residencePermitNumber')} onChange={set('residencePermitNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">
              BRP / visa expiry
              {identity.residencePermitExpiry && <span className="ml-2">{expiryChip(identity.residencePermitExpiry)}</span>}
            </label>
            <input type="date" className="field tabular-nums" value={val('residencePermitExpiry')} onChange={set('residencePermitExpiry')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Driving licence number" scan={findIdentityScan('driversLicenseNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned driving licence" />
            <input className="field font-mono tabular-nums" placeholder="Driving licence number" value={val('driversLicenseNumber')} onChange={set('driversLicenseNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">
              Driving licence expiry
              {identity.driversLicenseExpiry && <span className="ml-2">{expiryChip(identity.driversLicenseExpiry)}</span>}
            </label>
            <input type="date" className="field tabular-nums" value={val('driversLicenseExpiry')} onChange={set('driversLicenseExpiry')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="NHS number" scan={findIdentityScan('medicalAidNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned NHS card" />
            <input className="field font-mono tabular-nums" placeholder="NHS number" value={val('medicalAidNumber')} onChange={set('medicalAidNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">Registered GP practice</label>
            <input className="field" placeholder="e.g. The Oaks Surgery" value={val('registeredGpPractice')} onChange={set('registeredGpPractice')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Naturalisation certificate number" scan={findIdentityScan('citizenshipCertNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned naturalisation certificate" />
            <input className="field font-mono tabular-nums" placeholder="Certificate number" value={val('citizenshipCertNumber')} onChange={set('citizenshipCertNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
        </div>
      </div>
    </>
  );
}

function USFields({ identity, val, set, onChange, documents, onViewScan, memberName, onShowCard }: FieldSetProps) {
  return (
    <>
      {/* Identity */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-clay-600">
          <MapPin className="w-3 h-3" /> Identity
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label className="field-label">ID document type</label>
            <select
              className="field"
              value={val('idDocumentType')}
              onChange={(e) => onChange({ ...identity, idDocumentType: e.target.value || undefined })}
            >
              <option value="">Select…</option>
              <option value="State ID Card">State ID Card</option>
              <option value="State Driver's License">State Driver's License</option>
              <option value="Foreign passport">Foreign passport</option>
              <option value="Other">Other</option>
            </select>
          </div>
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">Social Security number</label>
              <div className="flex items-center gap-1">
                {identity.nationalIdNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'Social Security number', subtitle: memberName,
                      fields: [{ label: 'SSN', value: identity.nationalIdNumber || '—', mono: true, big: true }],
                      scanSrc: findIdentityScan('nationalIdNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this SSN"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input className="field font-mono tabular-nums" placeholder="e.g. 123-45-6789" value={val('nationalIdNumber')} onChange={set('nationalIdNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Unabridged birth certificate no." scan={findIdentityScan('birthCertNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned birth certificate" />
            <input className="field font-mono tabular-nums" placeholder="Birth certificate number" value={val('birthCertNumber')} onChange={set('birthCertNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Tax ID (if different from SSN)" scan={findIdentityScan('taxNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned tax document" />
            <input className="field font-mono tabular-nums" placeholder="ITIN / state tax ID" value={val('taxNumber')} onChange={set('taxNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Student number" scan={findIdentityScan('studentNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned student number document" />
            <input className="field font-mono tabular-nums" placeholder="Student number" value={val('studentNumber')} onChange={set('studentNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
        </div>
      </div>

      {/* Residence, travel & other */}
      <div className="space-y-3">
        <p className="section-label flex items-center gap-1.5 text-dusk-700">
          <BookOpen className="w-3 h-3" /> Residence, travel &amp; other
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[13px] font-semibold text-ink-600">Green Card / visa number</label>
              <div className="flex items-center gap-1">
                {identity.residencePermitNumber && (
                  <button
                    onClick={() => onShowCard({
                      title: 'Green Card / visa', subtitle: memberName,
                      fields: [
                        { label: 'Number', value: identity.residencePermitNumber || '—', mono: true, big: true },
                        ...(identity.residencePermitExpiry ? [{ label: 'Expiry', value: identity.residencePermitExpiry }] : []),
                      ],
                      scanSrc: findIdentityScan('residencePermitNumber', documents)?.fileData,
                    })}
                    className="flex items-center gap-1 text-[11px] font-semibold text-clay-600 hover:text-clay-800"
                    title="Show this Green Card/visa"
                  >
                    <Maximize2 className="w-3 h-3" /> Show
                  </button>
                )}
              </div>
            </div>
            <input className="field font-mono tabular-nums" placeholder="Green Card / visa number" value={val('residencePermitNumber')} onChange={set('residencePermitNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">
              Green Card / visa expiry
              {identity.residencePermitExpiry && <span className="ml-2">{expiryChip(identity.residencePermitExpiry)}</span>}
            </label>
            <input type="date" className="field tabular-nums" value={val('residencePermitExpiry')} onChange={set('residencePermitExpiry')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Driver's license number" scan={findIdentityScan('driversLicenseNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned driver's license" />
            <input className="field font-mono tabular-nums" placeholder="Driver's license number" value={val('driversLicenseNumber')} onChange={set('driversLicenseNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">
              Driver's license expiry
              {identity.driversLicenseExpiry && <span className="ml-2">{expiryChip(identity.driversLicenseExpiry)}</span>}
            </label>
            <input type="date" className="field tabular-nums" value={val('driversLicenseExpiry')} onChange={set('driversLicenseExpiry')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Health insurance member ID" scan={findIdentityScan('medicalAidNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned health insurance card" />
            <input className="field font-mono tabular-nums" placeholder="Health insurance member ID" value={val('medicalAidNumber')} onChange={set('medicalAidNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">Insurer / plan name</label>
            <input className="field" placeholder="e.g. Blue Cross Blue Shield PPO" value={val('medicalAidScheme')} onChange={set('medicalAidScheme')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">Group number</label>
            <input className="field font-mono tabular-nums" placeholder="Group #" value={val('insuranceGroupNumber')} onChange={set('insuranceGroupNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <label className="field-label">Plan type</label>
            <input className="field" placeholder="e.g. HMO — referral needed for specialists" value={val('medicalAidPlanOption')} onChange={set('medicalAidPlanOption')} onBlur={() => onChange({ ...identity })} />
          </div>
          <div>
            <IdentityLabelRow label="Certificate of Naturalization no." scan={findIdentityScan('citizenshipCertNumber', documents)} onViewScan={onViewScan} viewTitle="View scanned naturalization certificate" />
            <input className="field font-mono tabular-nums" placeholder="Certificate number" value={val('citizenshipCertNumber')} onChange={set('citizenshipCertNumber')} onBlur={() => onChange({ ...identity })} />
          </div>
        </div>
      </div>
    </>
  );
}

/* ─── Main export ────────────────────────────────────────────────── */

// Fold a legacy single passport (member.passport, from the old separate Passport
// tab) into the plural passports[] list so nothing is lost now the tabs are merged.
// Deduped by passport number, so it never shows twice.
function foldPassports(member: FamilyMember): PassportRecord[] {
  const list = [...(member.passports ?? [])];
  const lg = member.passport;
  if (lg?.passportNumber && !list.some(p => p.number === lg.passportNumber)) {
    list.push({
      id: 'legacy-' + lg.passportNumber,
      country: lg.issuingCountry || '',
      number: lg.passportNumber,
      expiryDate: lg.expiryDate || undefined,
      issueDate: lg.issueDate || undefined,
      notes: [lg.fullName ? `Name: ${lg.fullName}` : '', lg.notes || ''].filter(Boolean).join(' · ') || undefined,
    });
  }
  return list;
}

export default function MemberIDs({ member, onUpdate, onAddDocument, country = 'AT', onOpenPrivacy }: MemberIDsProps) {
  const [passports, setPassports] = useState<PassportRecord[]>(() => foldPassports(member));
  const [identity, setIdentity] = useState<IdentityRecord>(member.identity ?? {});
  const [viewScanSrc, setViewScanSrc] = useState<string | null>(null);
  const [showCard, setShowCard] = useState<ShowCardData | null>(null);
  const [scannerOpen, setScannerOpen] = useState(false);

  const handleScanResult = (file: ScannedFile) => {
    onAddDocument(member.id, {
      id: 'doc-' + Date.now().toString(),
      name: `${member.name}'s ID scan`,
      category: 'ID',
      fileType: file.type,
      fileName: file.name,
      fileSize: file.size,
      uploadedAt: new Date().toLocaleDateString('en-CA'),
      fileData: file.data,
    });
  };

  // Reset when switching members
  useEffect(() => {
    setPassports(foldPassports(member));
    setIdentity(member.identity ?? {});
  }, [member.id]);

  const handlePassportsChange = (next: PassportRecord[]) => {
    setPassports(next);
    onUpdate({ passports: next });
  };

  const handleIdentityChange = (next: IdentityRecord) => {
    setIdentity(next);
    onUpdate({ identity: next });
  };

  return (
    <div className="space-y-6 font-sans">
      <PrivacyNote onOpenPrivacy={onOpenPrivacy}>
        Only signed-in members of your family can see this — it's stored securely and isolated to your family space.
      </PrivacyNote>

      <PassportsSection
        passports={passports}
        onChange={handlePassportsChange}
        documents={member.documents}
        onViewScan={setViewScanSrc}
        memberName={member.name}
        onShowCard={setShowCard}
      />

      <ImageLightbox src={viewScanSrc} onClose={() => setViewScanSrc(null)} />
      <IdentitySection
        identity={identity}
        onChange={handleIdentityChange}
        documents={member.documents}
        onViewScan={setViewScanSrc}
        memberName={member.name}
        onShowCard={setShowCard}
        country={country}
        onScanClick={() => setScannerOpen(true)}
      />
      <DocumentScannerModal
        open={scannerOpen}
        onClose={() => setScannerOpen(false)}
        onUse={handleScanResult}
        title="Scan ID card"
        scanType="id"
      />

      <ShowCardModal
        open={!!showCard}
        onClose={() => setShowCard(null)}
        title={showCard?.title || ''}
        subtitle={showCard?.subtitle}
        fields={showCard?.fields}
        scanSrc={showCard?.scanSrc}
      />
    </div>
  );
}
