// Resolving a passport record to its scanned page — ONE implementation,
// shared by the profile's IDs tab and the travel pack.
//
// It lived inside MemberIDs.tsx first, which produced exactly the bug the
// extraction exists to prevent: the IDs tab found a saved scan by these
// heuristics while the trip pack honoured only the explicit photoDocId link,
// so the same passport showed its page on one screen and nothing on the
// other ("why isn't this autopulling — we have his passport saved").

import type { FamilyDocument, FamilyMember, IdentityRecord, PassportRecord } from '../types';

// Common ways a country ends up written — the passport record's "country"
// field is free text (typed by a person or generated by the AI) and a scanned
// document's name is a SEPARATE piece of free text, so "United Kingdom" and
// "UK" need to be recognized as the same country even though neither string
// literally contains the other. Anything not listed here still falls back to
// plain substring matching below, so this can only ever improve a match,
// never break one.
const COUNTRY_ALIASES: Record<string, string[]> = {
  uk: ['united kingdom', 'great britain', 'britain', 'england', 'scotland', 'wales', 'northern ireland', 'uk', 'gb'],
  za: ['south africa', 'south african', 'rsa', 'za'],
  at: ['austria', 'austrian', 'österreich', 'at'],
  us: ['united states', 'america', 'american', 'usa', 'us'],
  de: ['germany', 'german', 'deutschland', 'de'],
  fr: ['france', 'french', 'fr'],
  ie: ['ireland', 'irish', 'ie'],
  au: ['australia', 'australian', 'au'],
  ca: ['canada', 'canadian', 'ca'],
  nz: ['new zealand', 'nz'],
};

export function countryToken(raw: string): string | undefined {
  const s = raw.toLowerCase();
  for (const [token, aliases] of Object.entries(COUNTRY_ALIASES)) {
    if (aliases.some(a => s.includes(a))) return token;
  }
  return undefined;
}

/** The bits of a passport record the resolution actually reads — callers pass
 *  a full PassportRecord or the trimmed shape the trip checklist builds. */
export interface PassportScanKey {
  photoDocId?: string;
  country?: string;
}

/**
 * Link a passport to its scanned image among `docs`.
 *
 * An explicitly attached photo (photoDocId) wins over every guess below.
 * The heuristics exist for passports saved before a photo could be attached
 * at all, and they are guesses — matching on a document's NAME. Once someone
 * has actually pointed at the page, there is nothing left to infer.
 *
 * `docs` is whatever catalogue the caller can see: the member's own
 * documents, and optionally the shared vault's documents for that member
 * mapped through toFamilyDoc (vault "Identity" maps to "ID", downloadUrl
 * rides in fileData, so both stores match the same way).
 */
export function findPassportScan(p: PassportScanKey, docs?: FamilyDocument[]): FamilyDocument | undefined {
  if (p.photoDocId) {
    const exact = (docs || []).find(d => d.id === p.photoDocId && d.fileData);
    if (exact) return exact;
  }
  const idDocs = (docs || []).filter(d => d.category === 'ID' && d.fileData && /passport/i.test(d.name));
  if (idDocs.length === 0) return undefined;
  const country = (p.country || '').toLowerCase();
  const token = country ? countryToken(country) : undefined;
  const byAlias = token ? idDocs.find(d => countryToken(d.name) === token) : undefined;
  return byAlias
    || (country ? idDocs.find(d => d.name.toLowerCase().includes(country)) : undefined)
    || (idDocs.length === 1 ? idDocs[0] : undefined);
}

/**
 * The same resolution for a visa record — because the same bug happened
 * again one row down: a passport auto-pulls its scan, so the visa row
 * sitting under it LOOKS like it should too, and "why doesn't his temporary
 * residence card show here" is the entirely reasonable question when it
 * doesn't. A residence permit or card is the visa in practice, so the name
 * match covers the physical things people scan: visa stickers, residence
 * cards/permits, Aufenthaltstitel. "passport" names are excluded — a
 * passport scan may CONTAIN the visa sticker but it is the passport row's
 * card, and one file must not answer for two different documents.
 */
/**
 * Every saved birth certificate in the pool — plural, unlike the two finders
 * above: a family routinely holds both the original AND an apostilled copy,
 * and for a border crossing the apostilled one is not a duplicate of the
 * other, so the row shows every one it finds rather than guessing a winner.
 * Name-only matching, no category filter: certificates get filed under
 * Identity, Travel or Other depending on who saved them, but nothing except
 * a birth certificate is ever NAMED one.
 */
export function findBirthCertificateScans(docs?: FamilyDocument[]): FamilyDocument[] {
  return (docs || []).filter(d => d.fileData && /birth\s*certificate|geburtsurkunde|unabridged|\bubc\b/i.test(d.name));
}

export function findVisaScan(v: { country?: string }, docs?: FamilyDocument[]): FamilyDocument | undefined {
  const pool = (docs || []).filter(d =>
    (d.category === 'ID' || d.category === 'Travel')
    && d.fileData
    && /visa|residence|aufenthalt|permit/i.test(d.name)
    && !/passport/i.test(d.name));
  if (pool.length === 0) return undefined;
  const country = (v.country || '').toLowerCase();
  const token = country ? countryToken(country) : undefined;
  const byAlias = token ? pool.find(d => countryToken(d.name) === token) : undefined;
  return byAlias
    || (country ? pool.find(d => d.name.toLowerCase().includes(country)) : undefined)
    || (pool.length === 1 ? pool[0] : undefined);
}

// Moved from MemberIDs.tsx (where this and findIdentityScan below first
// lived) for the same reason findPassportScan/findVisaScan were extracted
// above: a second surface (MemberIdOverview.tsx's "every ID number AND every
// document" screen) needs the identical heuristic, and a pure utils module is
// something a standalone assertion test can import without dragging in
// React/Firebase — MemberIDs.tsx re-exports both names so existing importers
// (HealthInsuranceRow.tsx) are unaffected.
//
// Each identity field maps to a keyword pattern its scanned document's name
// is expected to match (English or German).
const IDENTITY_SCAN_PATTERNS: Partial<Record<keyof IdentityRecord, RegExp>> = {
  eCardNumber: /e-?card/i,
  taxNumber: /tax|steuer|sars/i,
  studentNumber: /student|matrikel/i,
  schoolRegNumber: /school|sch(?:ü|ue)ler/i,
  residencePermitNumber: /residence|aufenthalt|visa|permit/i,
  nationalIdNumber: /national\s*id|id\s*card|personalausweis|smart id|id book/i,
  citizenshipCertNumber: /citizenship|staatsb(?:ü|ue)rger/i,
  driversLicenseNumber: /driver|f(?:ü|ue)hrerschein/i,
  birthCertNumber: /birth cert/i,
  medicalAidNumber: /medical aid|health insurance/i,
};

export function findIdentityScan(field: keyof IdentityRecord, docs?: FamilyDocument[]): FamilyDocument | undefined {
  const pattern = IDENTITY_SCAN_PATTERNS[field];
  if (!pattern) return undefined;
  const idDocs = (docs || []).filter(d => d.category === 'ID' && d.fileData);
  let candidates = idDocs.filter(d => pattern.test(d.name));
  // The generic "national ID" field also catches anything explicitly labelled "ID"
  // as its own word — "Nomvula ID", "Mama ID and Driver's License" — the single
  // most common way people actually name an ID-document scan. This ADDS to (never
  // replaces) the specific-pattern match above, so a combined "ID and Driver's
  // License" scan surfaces under both fields rather than whichever keyword the
  // regex happened to hit first.
  if (field === 'nationalIdNumber') {
    const idLabelled = idDocs.filter(d => /\bid\b/i.test(d.name));
    candidates = [...new Set([...candidates, ...idLabelled])];
  }
  if (candidates.length === 0) return undefined;
  if (candidates.length === 1) return candidates[0];
  return [...candidates].sort((a, b) => (b.uploadedAt || '').localeCompare(a.uploadedAt || ''))[0];
}

// Fold a legacy single passport (member.passport, from the old separate Passport
// tab) into the plural passports[] list so nothing is lost now the tabs are merged.
// Deduped by passport number, so it never shows twice. Moved from MemberIDs.tsx
// alongside findIdentityScan above, for the same reason.
export function foldPassports(member: FamilyMember): PassportRecord[] {
  const list = [...(member.passports ?? [])];
  const lg = member.passport;
  if (lg?.passportNumber && !list.some(p => p.number === lg.passportNumber)) {
    list.push({
      id: 'legacy-' + lg.passportNumber,
      country: lg.issuingCountry || '',
      number: lg.passportNumber,
      expiryDate: lg.expiryDate || undefined,
      issueDate: lg.issueDate || undefined,
      notes: [lg.fullName ? `Name: ${lg.fullName}` : '', lg.notes || ''].filter(Boolean).join(' · ') || undefined,
    });
  }
  return list;
}
